let movieData = [
  {
    id : 0,
    title : "스파이더맨",
    posterImg : "/assets/posterImg1.png",
    open :  true,
    summary : "",
  },
  {
    id : 1,
    title : "스파이더맨2",
    posterImg : "/assets/posterImg2.png",
    open :  true,
    summary : "",
  },
  {
    id : 2,
    title : "아이언맨",
    posterImg : "/assets/posterImg3.png",
    open :  true,
    summary : "",
  },
  {
    id : 3,
    title : "아이언맨2",
    posterImg : "/assets/posterImg4.png",
    open :  true,
    summary : "",
  },
  {
    id : 4,
    title : "아이언맨3",
    posterImg : "/assets/posterImg5.png",
    open :  true,
    summary : "",
  },
  {
    id : 5,
    title : "존윅",
    posterImg : "/assets/posterImg6.png",
    open :  true,
    summary : "",
  },
  {
    id : 6,
    title : "기생충",
    posterImg : "/assets/posterImg7.png",
    open :  true,
    summary : "",
  },
  {
    id : 7,
    title : "탑건",
    posterImg : "/assets/posterImg8.png",
    open :  true,
    summary : "",
  },
  {
    id : 8,
    title : "탑건2",
    posterImg : "/assets/posterImg9.png",
    open :  true,
    summary : "",
  },
  {
    id : 9,
    title : "어벤저스",
    posterImg : "/assets/posterImg10.png",
    open :  true,
    summary : "",
  },
  {
    id : 10,
    title : "어벤저스2",
    posterImg : "/assets/posterImg11.png",
    open :  true,
    summary : "",
  },
  {
    id : 11,
    title : "짱구는 못말려",
    posterImg : "/assets/posterImg12.png",
    open :  true,
    summary : "",
  },
  {
    id : 12,
    title : "범죄도시",
    posterImg : "/assets/posterImg13.png",
    open :  true,
    summary : "",
  },
  {
    id : 13,
    title : "범죄도시2",
    posterImg : "/assets/posterImg14.png",
    open :  true,
    summary : "",
  },
  {
    id : 14,
    title : "이웃사람",
    posterImg : "/assets/posterImg15.png",
    open :  true,
    summary : "",
  },
  {
    id : 15,
    title : "리틀포레스트",
    posterImg : "/assets/posterImg16.png",
    open :  true,
    summary : "",
  },
  {
    id : 16,
    title : "써니",
    posterImg : "/assets/posterImg17.png",
    open :  true,
    summary : "",
  },
  {
    id : 17,
    title : "매트릭스",
    posterImg : "/assets/posterImg18.png",
    open :  true,
    summary : "",
  },
  {
    id : 18,
    title : "쇼생크 탈출",
    posterImg : "/assets/posterImg19.png",
    open :  true,
    summary : "",
  },
  {
    id : 19,
    title : "시계태엽 오렌지",
    posterImg : "/assets/posterImg20.png", 
    open :  true,
    summary : "",
  },
  {
    id : 20,
    title : "타이타닉",
    posterImg : "/assets/posterImg21.png",
    open :  true,
    summary : "",
  },
  {
    id : 21,
    title : "라따뚜이",
    posterImg : "/assets/posterImg22.png",
    open :  true,
    summary : "",
  },
  {
    id : 22,
    title : "겨울왕국",
    posterImg : "/assets/posterImg23.png",
    open :  true,
    summary : "",
  },
  {
    id : 23,
    title : "인셉션",
    posterImg : "/assets/posterImg24.png",
    open :  true,
    summary : "",
  },
  {
    id : 24,
    title : "인생은 아름다워",
    posterImg : "/assets/posterImg25.png",
    open :  true,
    summary : "",
  },
  {
    id : 25,
    title : "그랜드 부다페스트 호텔",
    posterImg : "/assets/posterImg26.png",
    open :  true,
    summary : "",
  },
  {
    id : 26,
    title : "설국열차",
    posterImg : "/assets/posterImg27.png",
    open :  true,
    summary : "",
  },
]

export default movieData;
