let movieData = [
  {
    id : 0,
    title : "보라색산1",
    posterImg : "/assets/posterImg1.png",
    open :  true,
  },
  {
    id : 1,
    title : "보라색산2",
    posterImg : "/assets/posterImg2.png",
    open :  true,
  },
  {
    id : 2,
    title : "보라색산3",
    posterImg : "/assets/posterImg3.png",
    open :  true,
  },
  {
    id : 3,
    title : "보라색산4",
    posterImg : "/assets/posterImg4.png",
    open :  true,
  },
  {
    id : 4,
    title : "보라색산5",
    posterImg : "/assets/posterImg5.png",
    open :  true,
  },
  {
    id : 5,
    title : "보라색산6",
    posterImg : "/assets/posterImg6.png",
    open :  true,
  },
  {
    id : 6,
    title : "보라색산7",
    posterImg : "/assets/posterImg7.png",
    open :  true,
  },
  {
    id : 7,
    title : "보라색산8",
    posterImg : "/assets/posterImg8.png",
    open :  true,
  },
  {
    id : 8,
    title : "보라색산9",
    posterImg : "/assets/posterImg9.png",
    open :  true,
  },
  {
    id : 9,
    title : "보라색산10",
    posterImg : "/assets/posterImg10.png",
    open :  true,
  },
  {
    id : 10,
    title : "보라색산11",
    posterImg : "/assets/posterImg11.png",
    open :  true,
  },
  {
    id : 11,
    title : "보라색산12",
    posterImg : "/assets/posterImg12.png",
    open :  true,
  },
  {
    id : 12,
    title : "보라색산13",
    posterImg : "/assets/posterImg13.png",
    open :  true,
  },
  {
    id : 13,
    title : "보라색산14",
    posterImg : "/assets/posterImg14.png",
    open :  true,
  },
  {
    id : 14,
    title : "보라색산15",
    posterImg : "/assets/posterImg15.png",
    open :  true,
  },
  {
    id : 15,
    title : "보라색산16",
    posterImg : "/assets/posterImg16.png",
    open :  true,
  },
  {
    id : 16,
    title : "보라색산17",
    posterImg : "/assets/posterImg17.png",
    open :  true,
  },
  {
    id : 17,
    title : "보라색산18",
    posterImg : "/assets/posterImg18.png",
    open :  true,
  },
  {
    id : 18,
    title : "보라색산19",
    posterImg : "/assets/posterImg19.png",
    open :  true,
  },
  {
    id : 19,
    title : "보라색산20",
    posterImg : "/assets/posterImg20.png", 
    open :  true,
  },
  {
    id : 20,
    title : "보라색산21",
    posterImg : "/assets/posterImg21.png",
    open :  true,
  },
  {
    id : 21,
    title : "보라색산22",
    posterImg : "/assets/posterImg22.png",
    open :  true,
  },
  {
    id : 22,
    title : "보라색산23",
    posterImg : "/assets/posterImg23.png",
    open :  true,
  },
  {
    id : 23,
    title : "보라색산24",
    posterImg : "/assets/posterImg24.png",
    open :  true,
  },
  {
    id : 24,
    title : "보라색산25",
    posterImg : "/assets/posterImg25.png",
    open :  true,
  },
  {
    id : 25,
    title : "보라색산26",
    posterImg : "/assets/posterImg26.png",
    open :  true,
  },
  {
    id : 26,
    title : "보라색산26",
    posterImg : "/assets/posterImg27.png",
    open :  true,
  },
]

export default movieData;
